## Purpose
1. To remove rows where both RefSeq ID = "-" and GENECODEID = "-" 
2. To remove all rows that contain hypothetical
3. To remove all other theoretical | outlaws
3. To create a new file that satisfy both #1 and #2

In [1]:
import pandas as pd

In [2]:
f_iso_all = "iso_all_v1.1.csv"
df_iso_all = pd.read_csv(f_iso_all)
df_iso_all

,CHESS ID,GENE,RefSeq ID,GENCODE ID,pLDDT,introns in mouse
0,CHS.15.1,OR4F29,rna-NM_001005221.2,ENST00000426406.4,88.2,no_introns
1,CHS.39.7,SAMD11,rna-NM_001385641.1,ENST00000616016.5,46.4,False
2,CHS.40.3,NOC2L,rna-NM_015658.4,ENST00000327044.7,71.1,False
3,CHS.41.11,PLEKHN1,rna-NM_032129.3,ENST00000379410.8,49.4,False
4,CHS.42.6,KLHL17,rna-NM_198317.3,ENST00000338591.8,86.3,True
...,...,...,...,...,...,...
194775,hypothetical.2081.1,-,rna-NM_001005182.2,ENST00000642104.1,88.9,True
194776,hypothetical.2082.1,-,rna-NM_001348233.2,ENST00000540461.2,83.2,False
194777,hypothetical.2083.1,-,rna-NM_001005166.5,ENST00000610445.2,83.5,False
194778,hypothetical.2084.1,-,rna-NM_001005468.2,ENST00000641451.2,89.3,True
194779,hypothetical.2085.1,-,rna-NM_001369203.1,ENST00000494082.3,75.6,False

In [3]:
# Check that all CHESS ID are unique
df_iso_all["CHESS ID"].value_counts()

CHS.12322.8       1
CHS.17999.8       1
CHS.37787.12      1
CHS.17009.alt8    1
CHS.49846.13      1
                 ..
CHS.41916.10      1
CHS.20181.16      1
CHS.40697.alt7    1
CHS.24311.12      1
CHS.26516.3       1
Name: CHESS ID, Length: 194780, dtype: int64

In [4]:
 # Getting to know the data
df_iso_all["GENE"].value_counts()

-            26704
MAPK10         129
ABI2           117
MBNL1          109
RAP1GAP        106
             ...
KRTAP10-2        1
OR10Q1           1
EN2              1
KRTAP20-2        1
CT47A7           1
Name: GENE, Length: 16124, dtype: int64

### 1. Keep only rows where there is transcript info in at least one of RefSeq and GENCODE

In [5]:
# Show rows where RefSeq ID exist (not "-")
df_iso_all[df_iso_all["RefSeq ID"] != "-"].sample(20)

,CHESS ID,GENE,RefSeq ID,GENCODE ID,pLDDT,introns in mouse
144169,CHS.43537.1,NUDT12,rna-XM_005272095.1,-,86.7,True
11040,CHS.41970.1,PRIMPOL,rna-NM_152683.4,ENST00000314970.11,72.5,False
108664,CHS.30673.8,CFAP221,rna-XR_001738665.1,-,68.7,False
1895,CHS.6813.1,FGFBP3,rna-NM_152429.5,ENST00000311575.6,64.6,True
6372,CHS.23285.5,TRIM47,rna-NM_033452.3,ENST00000254816.6,81.5,True
88889,CHS.23565.10,ARHGDIA,rna-NM_001301240.2,ENST00000584461.5,59.2,False
63662,CHS.15379.3,-,rna-NR_131765.2,ENST00000557423.5,59.9,False
24920,CHS.2519.12,DENND2D,rna-XM_017002387.1,-,90.5,True
89299,CHS.23650.1,B3GNTL1,rna-NR_135466.2,ENST00000572977.5,94.3,False
129880,CHS.37927.13,BBX,rna-XM_017006882.1,-,44.8,True
39581,CHS.7433.8,CHST15,rna-XM_017016319.1,-,79.5,False
18789,CHS.806.7,GRHL3,rna-XM_011541870.2,-,67.9,True
98039,CHS.26681.9,SAMD4B,rna-NM_001384576.1,-,60.8,False
3791,CHS.12974.4,SRSF9,rna-NM_003769.3,ENST00000229390.8,66.1,True
150215,CHS.46096.8,TAPBP,rna-NM_172208.3,ENST00000426633.6,81.8,True
32769,CHS.5240.15,ZNF692,rna-XM_011544223.2,-,67.0,False
102054,CHS.27633.5,SBK3,rna-XM_011526298.2,-,82.6,False
80732,CHS.21079.3,-,rna-XM_006721519.3,-,57.9,False
170178,CHS.55358.10,CNTFR,rna-XM_017014265.1,-,81.8,True
35745,CHS.6393.30,COL13A1,rna-NM_001130103.2,ENST00000398978.8,50.3,True

In [6]:
# Show rows where GENECODE ID exist (not "-")
df_iso_all[df_iso_all["GENCODE ID"] != "-"].sample(20)

,CHESS ID,GENE,RefSeq ID,GENCODE ID,pLDDT,introns in mouse
159379,CHS.51114.15,SLC25A40,-,ENST00000496348.5,72.0,True
77406,CHS.20085.alt1,CKLF,-,ENST00000527845.1,68.5,False
106289,CHS.29897.alt4,RTKN,-,ENST00000464094.2,90.9,True
22260,CHS.1661.6,DIO1,rna-NR_136692.2,ENST00000530084.5,93.5,True
10492,CHS.39605.14,PIGG,rna-NM_001127178.3,ENST00000453061.7,83.9,True
176370,CHS.57676.alt5,PHEX,-,ENST00000682888.1,92.7,False
138548,CHS.41055.4,AIMP1,rna-NM_004757.4,ENST00000358008.7,79.9,True
14047,CHS.56652.5,STOM,rna-NM_004099.6,ENST00000286713.7,85.2,True
113776,CHS.32348.28,COPS7B,-,ENST00000488111.1,84.4,True
59784,CHS.13582.13,-,-,ENST00000474317.1,54.4,True
89177,CHS.23629.5,CYBC1,rna-NM_001100408.3,ENST00000434650.6,69.7,False
45001,CHS.9064.4,SLC22A12,rna-NM_001276327.2,ENST00000377572.5,83.9,True
1513,CHS.4994.2,RBM34,rna-NM_015014.4,ENST00000408888.8,66.6,True
224,CHS.720.1,WNT4,rna-NM_030761.5,ENST00000290167.11,90.2,True
193725,CHS.56847.16,DNM1,-,ENST00000628346.2,78.0,False
153788,CHS.47331.19,-,-,ENST00000617072.4,80.7,True
4896,CHS.18102.2,TM6SF1,rna-NM_023003.5,ENST00000322019.14,90.0,True
19703,CHS.1082.1,KHDRBS1,rna-NR_073498.2,ENST00000307714.12,64.1,False
41666,CHS.8061.9,WEE1,rna-NM_001143976.2,ENST00000299613.10,78.0,False
6461,CHS.23590.8,DCXR,rna-NM_016286.4,ENST00000306869.7,94.9,True

In [7]:
# Count the number of rows where both RefSeq and GENCODE ID are "-"
df_iso_all[(df_iso_all["RefSeq ID"] == "-") & (df_iso_all["GENCODE ID"] == "-")]

,CHESS ID,GENE,RefSeq ID,GENCODE ID,pLDDT,introns in mouse
16222,CHS.10.alt1,-,-,-,61.1,False
16223,CHS.10.alt2,-,-,-,66.8,False
16224,CHS.10.alt3,-,-,-,66.8,False
16225,CHS.10.alt4,-,-,-,66.8,False
16226,CHS.10.alt5,-,-,-,66.8,False
...,...,...,...,...,...,...
194448,hypothetical.1794.1,CLIC2,-,-,85.9,False
194449,hypothetical.1794.2,CLIC2,-,-,43.2,False
194452,hypothetical.1796.1,-,-,-,50.8,False
194453,hypothetical.1796.2,-,-,-,49.9,False
194462,hypothetical.2212.1,-,-,-,63.4,False

In [8]:
df_iso_all_RGExist = df_iso_all[(df_iso_all["RefSeq ID"] != "-") | (df_iso_all["GENCODE ID"] != "-")]
df_iso_all_RGExist

,CHESS ID,GENE,RefSeq ID,GENCODE ID,pLDDT,introns in mouse
0,CHS.15.1,OR4F29,rna-NM_001005221.2,ENST00000426406.4,88.2,no_introns
1,CHS.39.7,SAMD11,rna-NM_001385641.1,ENST00000616016.5,46.4,False
2,CHS.40.3,NOC2L,rna-NM_015658.4,ENST00000327044.7,71.1,False
3,CHS.41.11,PLEKHN1,rna-NM_032129.3,ENST00000379410.8,49.4,False
4,CHS.42.6,KLHL17,rna-NM_198317.3,ENST00000338591.8,86.3,True
...,...,...,...,...,...,...
194775,hypothetical.2081.1,-,rna-NM_001005182.2,ENST00000642104.1,88.9,True
194776,hypothetical.2082.1,-,rna-NM_001348233.2,ENST00000540461.2,83.2,False
194777,hypothetical.2083.1,-,rna-NM_001005166.5,ENST00000610445.2,83.5,False
194778,hypothetical.2084.1,-,rna-NM_001005468.2,ENST00000641451.2,89.3,True
194779,hypothetical.2085.1,-,rna-NM_001369203.1,ENST00000494082.3,75.6,False

In [9]:
# Check whether there are any rows containing "-" in both "RefSeq ID" and "GENCODE ID" cols
df_iso_all_RGExist[(df_iso_all_RGExist["RefSeq ID"] == "-") & (df_iso_all_RGExist["GENCODE ID"] == "-")]

Empty DataFrame
Columns: [CHESS ID, GENE, RefSeq ID, GENCODE ID, pLDDT, introns in mouse]
Index: []

In [10]:
print((58686+136094) == 194780)

True

### 2. Remove all hypothetical

In [11]:
df_iso_all_RGExist

,CHESS ID,GENE,RefSeq ID,GENCODE ID,pLDDT,introns in mouse
0,CHS.15.1,OR4F29,rna-NM_001005221.2,ENST00000426406.4,88.2,no_introns
1,CHS.39.7,SAMD11,rna-NM_001385641.1,ENST00000616016.5,46.4,False
2,CHS.40.3,NOC2L,rna-NM_015658.4,ENST00000327044.7,71.1,False
3,CHS.41.11,PLEKHN1,rna-NM_032129.3,ENST00000379410.8,49.4,False
4,CHS.42.6,KLHL17,rna-NM_198317.3,ENST00000338591.8,86.3,True
...,...,...,...,...,...,...
194775,hypothetical.2081.1,-,rna-NM_001005182.2,ENST00000642104.1,88.9,True
194776,hypothetical.2082.1,-,rna-NM_001348233.2,ENST00000540461.2,83.2,False
194777,hypothetical.2083.1,-,rna-NM_001005166.5,ENST00000610445.2,83.5,False
194778,hypothetical.2084.1,-,rna-NM_001005468.2,ENST00000641451.2,89.3,True
194779,hypothetical.2085.1,-,rna-NM_001369203.1,ENST00000494082.3,75.6,False

In [12]:
# Check the number of CHESS ID containing "hypothetical"
df_iso_all_RGExist[df_iso_all_RGExist["CHESS ID"].str.contains("hypothetical")]

,CHESS ID,GENE,RefSeq ID,GENCODE ID,pLDDT,introns in mouse
141,hypothetical.0.1,PRAMEF27,rna-NM_001300891.2,ENST00000436041.6,84.7,False
143,hypothetical.1.1,PRAMEF26,rna-NM_001306072.3,ENST00000624207.1,84.7,False
144,hypothetical.2.1,HNRNPCL4,rna-NM_001302551.2,ENST00000323770.8,65.2,no_introns
145,hypothetical.3.1,PRAMEF9,rna-NM_001010890.3,ENST00000415919.3,84.8,False
207,hypothetical.4.1,PLA2G2C,rna-NM_001367969.2,ENST00000679259.1,71.8,False
...,...,...,...,...,...,...
194775,hypothetical.2081.1,-,rna-NM_001005182.2,ENST00000642104.1,88.9,True
194776,hypothetical.2082.1,-,rna-NM_001348233.2,ENST00000540461.2,83.2,False
194777,hypothetical.2083.1,-,rna-NM_001005166.5,ENST00000610445.2,83.5,False
194778,hypothetical.2084.1,-,rna-NM_001005468.2,ENST00000641451.2,89.3,True
194779,hypothetical.2085.1,-,rna-NM_001369203.1,ENST00000494082.3,75.6,False

In [13]:
# Create a df where, from the output df from step 1, rows where CHESS ID column contains "hypothetical" are removed
df_iso_all_filtered = df_iso_all_RGExist[~df_iso_all_RGExist["CHESS ID"].str.contains("hypothetical")]
df_iso_all_filtered

,CHESS ID,GENE,RefSeq ID,GENCODE ID,pLDDT,introns in mouse
0,CHS.15.1,OR4F29,rna-NM_001005221.2,ENST00000426406.4,88.2,no_introns
1,CHS.39.7,SAMD11,rna-NM_001385641.1,ENST00000616016.5,46.4,False
2,CHS.40.3,NOC2L,rna-NM_015658.4,ENST00000327044.7,71.1,False
3,CHS.41.11,PLEKHN1,rna-NM_032129.3,ENST00000379410.8,49.4,False
4,CHS.42.6,KLHL17,rna-NM_198317.3,ENST00000338591.8,86.3,True
...,...,...,...,...,...,...
194662,CHS.34304.1,-,rna-NM_001386820.1,ENST00000624951.1,52.2,True
194664,CHS.613.1,-,rna-NM_152232.4,ENST00000375371.3,86.0,True
194665,CHS.10998.1,-,rna-NM_023922.1,-,82.1,no_introns
194666,CHS.11009.1,-,rna-NM_001097643.1,-,84.7,no_introns
194667,CHS.21724.1,-,rna-NM_004740.3,-,35.9,no_introns

In [17]:
df_iso_all_filtered["GENE"].value_countsounts()

-          14706
MAPK10       104
ABI2         103
MBNL1        102
CELF1         93
           ...
PPIAL4C        1
NGRN           1
FAM162B        1
TCERG1L        1
PDRG1          1
Name: GENE, Length: 15852, dtype: int64

In [14]:
print((3943+132151) == 136094)

True

In [15]:
f_out = "iso_all_v1.1.filtered.132151.csv"    # original: iso_all_v1.1.csv
df_iso_all_filtered.to_csv(f_out, index=None)  ####### I may want to remove the header

In [16]:
# Generate a textfile where each line contains the CHESS ID of remaining 132151 samples
f_out_filtered_CHESSID = "CHESS_ID_iso_all_v1.1.filtered.132151.txt"
df_iso_all_filtered["CHESS ID"].to_csv(f_out_filtered_CHESSID, index=None, header=None)