In [ ]:
# Purpose: To analyze result of pydca

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
f_base_gplmdca = "gplmDCA_protein_MSAsize_seqlen_bin_all.txt"
f_base_pydca = "pydca_protein_MSAsize_seqlen_bin_all.txt"
f_pydca = "output_pydca_all.txt"
f_gplmdca = "output_gplmDCA_all.txt"

In [3]:
df_base_gplmdca = pd.read_csv(f_base_gplmdca, names=["Filename", "MSA_size", "Sequence_length", "Bin"])
df_base_pydca = pd.read_csv(f_base_pydca, names=["Filename", "MSA_size", "Sequence_length", "Bin"])
df_gplmdca = pd.read_csv(f_gplmdca, names=["Filename", "Execution_time", "Bin"])
df_pydca = pd.read_csv(f_pydca, names=["Filename", "Execution_time", "Bin"])

### pydca

In [4]:
df_base_pydca

,Filename,MSA_size,Sequence_length,Bin
0,Trimmed_ENSP00000202556.msa.a3m.reformatted.fa,3056,89,1090_1099
1,Trimmed_ENSP00000205214.msa.a3m.reformatted.fa,6642,0,1090_1099
2,Trimmed_ENSP00000255194.msa.a3m.reformatted.fa,2920,400,1090_1099
3,Trimmed_ENSP00000261778.msa.a3m.reformatted.fa,1099,651,1090_1099
4,Trimmed_ENSP00000261892.msa.a3m.reformatted.fa,3194,0,1090_1099
...,...,...,...,...
795,Trimmed_ENSP00000505395.msa.a3m.reformatted.fa,1013,52,90_99
796,Trimmed_ENSP00000512455.msa.a3m.reformatted.fa,534,31,90_99
797,Trimmed_ENSP00000512643.msa.a3m.reformatted.fa,488,56,90_99
798,Trimmed_ENSP00000512834.msa.a3m.reformatted.fa,1033,70,90_99
799,Trimmed_ENSP00000512907.msa.a3m.reformatted.fa,102,66,90_99

In [5]:
df_base_pydca["Filename"] = df_base_pydca["Filename"].str.split('_').str[1].str.split('.').str[0]
df_base_pydca

            Filename  MSA_size  Sequence_length        Bin
0    ENSP00000202556      3056               89  1090_1099
1    ENSP00000205214      6642                0  1090_1099
2    ENSP00000255194      2920              400  1090_1099
3    ENSP00000261778      1099              651  1090_1099
4    ENSP00000261892      3194                0  1090_1099
..               ...       ...              ...        ...
795  ENSP00000505395      1013               52      90_99
796  ENSP00000512455       534               31      90_99
797  ENSP00000512643       488               56      90_99
798  ENSP00000512834      1033               70      90_99
799  ENSP00000512907       102               66      90_99

[800 rows x 4 columns]

## pydca

In [6]:
df_pydca

,Filename,Execution_time,Bin
0,NaN,0 h 0 min 2 s elapsed for process,1090_1099
1,Trimmed_ENSP00000202556.msa.a3m.reformatted.fa,0 h 0 min 25 s elapsed for process Trimmed_ENS...,1090_1099
2,Trimmed_ENSP00000205214.msa.a3m.reformatted.fa,0 h 0 min 2 s elapsed for process Trimmed_ENSP...,1090_1099
3,Trimmed_ENSP00000255194.msa.a3m.reformatted.fa,0 h 40 min 21 s elapsed for process Trimmed_EN...,1090_1099
4,Trimmed_ENSP00000261778.msa.a3m.reformatted.fa,1 h 53 min 55 s elapsed for process Trimmed_EN...,1090_1099
...,...,...,...
803,Trimmed_ENSP00000505395.msa.a3m.reformatted.fa,0 h 0 min 15 s elapsed for process Trimmed_ENS...,90_99
804,Trimmed_ENSP00000512455.msa.a3m.reformatted.fa,0 h 0 min 4 s elapsed for process Trimmed_ENSP...,90_99
805,Trimmed_ENSP00000512643.msa.a3m.reformatted.fa,0 h 0 min 10 s elapsed for process Trimmed_ENS...,90_99
806,Trimmed_ENSP00000512834.msa.a3m.reformatted.fa,0 h 0 min 26 s elapsed for process Trimmed_ENS...,90_99
807,Trimmed_ENSP00000512907.msa.a3m.reformatted.fa,0 h 0 min 5 s elapsed for process Trimmed_ENSP...,90_99

In [7]:
df_pydca["Filename"] = df_pydca["Filename"].str.split('_').str[1].str.split('.').str[0]
df_pydca

,Filename,Execution_time,Bin
0,NaN,0 h 0 min 2 s elapsed for process,1090_1099
1,ENSP00000202556,0 h 0 min 25 s elapsed for process Trimmed_ENS...,1090_1099
2,ENSP00000205214,0 h 0 min 2 s elapsed for process Trimmed_ENSP...,1090_1099
3,ENSP00000255194,0 h 40 min 21 s elapsed for process Trimmed_EN...,1090_1099
4,ENSP00000261778,1 h 53 min 55 s elapsed for process Trimmed_EN...,1090_1099
...,...,...,...
803,ENSP00000505395,0 h 0 min 15 s elapsed for process Trimmed_ENS...,90_99
804,ENSP00000512455,0 h 0 min 4 s elapsed for process Trimmed_ENSP...,90_99
805,ENSP00000512643,0 h 0 min 10 s elapsed for process Trimmed_ENS...,90_99
806,ENSP00000512834,0 h 0 min 26 s elapsed for process Trimmed_ENS...,90_99
807,ENSP00000512907,0 h 0 min 5 s elapsed for process Trimmed_ENSP...,90_99

In [8]:
print(df_pydca["Filename"].isna().sum())
df_pydca = df_pydca.dropna()
df_pydca

8

,Filename,Execution_time,Bin
1,ENSP00000202556,0 h 0 min 25 s elapsed for process Trimmed_ENS...,1090_1099
2,ENSP00000205214,0 h 0 min 2 s elapsed for process Trimmed_ENSP...,1090_1099
3,ENSP00000255194,0 h 40 min 21 s elapsed for process Trimmed_EN...,1090_1099
4,ENSP00000261778,1 h 53 min 55 s elapsed for process Trimmed_EN...,1090_1099
5,ENSP00000261892,0 h 0 min 2 s elapsed for process Trimmed_ENSP...,1090_1099
...,...,...,...
803,ENSP00000505395,0 h 0 min 15 s elapsed for process Trimmed_ENS...,90_99
804,ENSP00000512455,0 h 0 min 4 s elapsed for process Trimmed_ENSP...,90_99
805,ENSP00000512643,0 h 0 min 10 s elapsed for process Trimmed_ENS...,90_99
806,ENSP00000512834,0 h 0 min 26 s elapsed for process Trimmed_ENS...,90_99
807,ENSP00000512907,0 h 0 min 5 s elapsed for process Trimmed_ENSP...,90_99

In [9]:
df_pydca["h"] = df_pydca["Execution_time"].str.split('h').str[0]
df_pydca["m"] = df_pydca["Execution_time"].str.split('h').str[1].str.split('min').str[0]
df_pydca["s"] = df_pydca["Execution_time"].str.split('h').str[1].str.split('min').str[1].str.split('s').str[0]
df_pydca

C:\Users\Yumika\AppData\Local\Temp\ipykernel_1916\578114840.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pydca["h"] = df_pydca["Execution_time"].str.split('h').str[0]
C:\Users\Yumika\AppData\Local\Temp\ipykernel_1916\578114840.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pydca["m"] = df_pydca["Execution_time"].str.split('h').str[1].str.split('min').str[0]
C:\Users\Yumika\AppData\Local\Temp\ipykernel_1916\578114840.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pydca["s"] = df_pydca["Execution_time"].str.split('h').str[1].str.split('min').str[1].str.split('s').str[0]

,Filename,Execution_time,Bin,h,m,s
1,ENSP00000202556,0 h 0 min 25 s elapsed for process Trimmed_ENS...,1090_1099,0,0,25
2,ENSP00000205214,0 h 0 min 2 s elapsed for process Trimmed_ENSP...,1090_1099,0,0,2
3,ENSP00000255194,0 h 40 min 21 s elapsed for process Trimmed_EN...,1090_1099,0,40,21
4,ENSP00000261778,1 h 53 min 55 s elapsed for process Trimmed_EN...,1090_1099,1,53,55
5,ENSP00000261892,0 h 0 min 2 s elapsed for process Trimmed_ENSP...,1090_1099,0,0,2
...,...,...,...,...,...,...
803,ENSP00000505395,0 h 0 min 15 s elapsed for process Trimmed_ENS...,90_99,0,0,15
804,ENSP00000512455,0 h 0 min 4 s elapsed for process Trimmed_ENSP...,90_99,0,0,4
805,ENSP00000512643,0 h 0 min 10 s elapsed for process Trimmed_ENS...,90_99,0,0,10
806,ENSP00000512834,0 h 0 min 26 s elapsed for process Trimmed_ENS...,90_99,0,0,26
807,ENSP00000512907,0 h 0 min 5 s elapsed for process Trimmed_ENSP...,90_99,0,0,5

In [10]:
df_pydca["h"] = df_pydca["h"].astype(int)
df_pydca["m"] = df_pydca["m"].astype(int)
df_pydca["s"] = df_pydca["s"].astype(int)
#print(df_pydca.dtypes)
#print(df_pydca)

C:\Users\Yumika\AppData\Local\Temp\ipykernel_1916\726435457.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pydca["h"] = df_pydca["h"].astype(int)
C:\Users\Yumika\AppData\Local\Temp\ipykernel_1916\726435457.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pydca["m"] = df_pydca["m"].astype(int)
C:\Users\Yumika\AppData\Local\Temp\ipykernel_1916\726435457.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pydca["s"] = df_pydca["s"].astype(int)

In [11]:
df_pydca["Total_s"] = df_pydca["h"] * 3600 + df_pydca["m"] * 60 + df_pydca["s"]
df_pydca

C:\Users\Yumika\AppData\Local\Temp\ipykernel_1916\1159478689.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pydca["Total_s"] = df_pydca["h"] * 3600 + df_pydca["m"] * 60 + df_pydca["s"]

,Filename,Execution_time,Bin,h,m,s,Total_s
1,ENSP00000202556,0 h 0 min 25 s elapsed for process Trimmed_ENS...,1090_1099,0,0,25,25
2,ENSP00000205214,0 h 0 min 2 s elapsed for process Trimmed_ENSP...,1090_1099,0,0,2,2
3,ENSP00000255194,0 h 40 min 21 s elapsed for process Trimmed_EN...,1090_1099,0,40,21,2421
4,ENSP00000261778,1 h 53 min 55 s elapsed for process Trimmed_EN...,1090_1099,1,53,55,6835
5,ENSP00000261892,0 h 0 min 2 s elapsed for process Trimmed_ENSP...,1090_1099,0,0,2,2
...,...,...,...,...,...,...,...
803,ENSP00000505395,0 h 0 min 15 s elapsed for process Trimmed_ENS...,90_99,0,0,15,15
804,ENSP00000512455,0 h 0 min 4 s elapsed for process Trimmed_ENSP...,90_99,0,0,4,4
805,ENSP00000512643,0 h 0 min 10 s elapsed for process Trimmed_ENS...,90_99,0,0,10,10
806,ENSP00000512834,0 h 0 min 26 s elapsed for process Trimmed_ENS...,90_99,0,0,26,26
807,ENSP00000512907,0 h 0 min 5 s elapsed for process Trimmed_ENSP...,90_99,0,0,5,5

## gplmDCA

In [12]:
df_base_gplmdca

,Filename,MSA_size,Sequence_length,Bin
0,ENSP00000255194.filtered.countVal.a3m,334,1094,1090_1099
1,ENSP00000261778.filtered.countVal.a3m,766,1094,1090_1099
2,ENSP00000263409.filtered.countVal.a3m,311,1097,1090_1099
3,ENSP00000264160.filtered.countVal.a3m,137,1099,1090_1099
4,ENSP00000264868.filtered.countVal.a3m,195,1097,1090_1099
...,...,...,...,...
608,ENSP00000504562.filtered.countVal.a3m,989,90,90_99
609,ENSP00000505395.filtered.countVal.a3m,320,99,90_99
610,ENSP00000512455.filtered.countVal.a3m,139,95,90_99
611,ENSP00000512643.filtered.countVal.a3m,134,92,90_99
612,ENSP00000512834.filtered.countVal.a3m,818,96,90_99

In [13]:
df_base_gplmdca["Filename"] = df_base_gplmdca["Filename"].str.split('.').str[0]
df_base_gplmdca

            Filename  MSA_size  Sequence_length        Bin
0    ENSP00000255194       334             1094  1090_1099
1    ENSP00000261778       766             1094  1090_1099
2    ENSP00000263409       311             1097  1090_1099
3    ENSP00000264160       137             1099  1090_1099
4    ENSP00000264868       195             1097  1090_1099
..               ...       ...              ...        ...
608  ENSP00000504562       989               90      90_99
609  ENSP00000505395       320               99      90_99
610  ENSP00000512455       139               95      90_99
611  ENSP00000512643       134               92      90_99
612  ENSP00000512834       818               96      90_99

[613 rows x 4 columns]

In [14]:
df_gplmdca

,Filename,Execution_time,Bin
0,NaN,0 min 14 s elapsed for process 0 h 0 min 14 s ...,1090_1099
1,ENSP00000255194.filtered.countVal.a3m,58 min 52 s elapsed for process 10 h 58 min 52...,1090_1099
2,ENSP00000261778.filtered.countVal.a3m,1 min 18 s elapsed for process 17 h 1 min 18 s...,1090_1099
3,ENSP00000263409.filtered.countVal.a3m,29 min 49 s elapsed for process 14 h 29 min 49...,1090_1099
4,ENSP00000264160.filtered.countVal.a3m,18 min 10 s elapsed for process 9 h 18 min 10 ...,1090_1099
...,...,...,...
616,ENSP00000504562.filtered.countVal.a3m,3 min 31 s elapsed for process 0 h 3 min 31 s ...,90_99
617,ENSP00000505395.filtered.countVal.a3m,2 min 5 s elapsed for process 0 h 2 min 5 s el...,90_99
618,ENSP00000512455.filtered.countVal.a3m,1 min 19 s elapsed for process 0 h 1 min 19 s ...,90_99
619,ENSP00000512643.filtered.countVal.a3m,Minimizing g_r for node r=92 Minimizing g_r fo...,90_99
620,ENSP00000512834.filtered.countVal.a3m,1 min 53 s elapsed for process 0 h 1 min 53 s ...,90_99

In [15]:
df_gplmdca["Filename"] = df_gplmdca["Filename"].str.split('.').str[0]
df_gplmdca

,Filename,Execution_time,Bin
0,NaN,0 min 14 s elapsed for process 0 h 0 min 14 s ...,1090_1099
1,ENSP00000255194,58 min 52 s elapsed for process 10 h 58 min 52...,1090_1099
2,ENSP00000261778,1 min 18 s elapsed for process 17 h 1 min 18 s...,1090_1099
3,ENSP00000263409,29 min 49 s elapsed for process 14 h 29 min 49...,1090_1099
4,ENSP00000264160,18 min 10 s elapsed for process 9 h 18 min 10 ...,1090_1099
...,...,...,...
616,ENSP00000504562,3 min 31 s elapsed for process 0 h 3 min 31 s ...,90_99
617,ENSP00000505395,2 min 5 s elapsed for process 0 h 2 min 5 s el...,90_99
618,ENSP00000512455,1 min 19 s elapsed for process 0 h 1 min 19 s ...,90_99
619,ENSP00000512643,Minimizing g_r for node r=92 Minimizing g_r fo...,90_99
620,ENSP00000512834,1 min 53 s elapsed for process 0 h 1 min 53 s ...,90_99

In [16]:
print(df_gplmdca["Filename"].isna().sum())
df_gplmdca = df_gplmdca.dropna()
df_gplmdca

8

,Filename,Execution_time,Bin
1,ENSP00000255194,58 min 52 s elapsed for process 10 h 58 min 52...,1090_1099
2,ENSP00000261778,1 min 18 s elapsed for process 17 h 1 min 18 s...,1090_1099
3,ENSP00000263409,29 min 49 s elapsed for process 14 h 29 min 49...,1090_1099
4,ENSP00000264160,18 min 10 s elapsed for process 9 h 18 min 10 ...,1090_1099
5,ENSP00000264868,11 min 5 s elapsed for process 5 h 11 min 5 s ...,1090_1099
...,...,...,...
616,ENSP00000504562,3 min 31 s elapsed for process 0 h 3 min 31 s ...,90_99
617,ENSP00000505395,2 min 5 s elapsed for process 0 h 2 min 5 s el...,90_99
618,ENSP00000512455,1 min 19 s elapsed for process 0 h 1 min 19 s ...,90_99
619,ENSP00000512643,Minimizing g_r for node r=92 Minimizing g_r fo...,90_99
620,ENSP00000512834,1 min 53 s elapsed for process 0 h 1 min 53 s ...,90_99

In [17]:
df_gplmdca["h"] = df_gplmdca["Execution_time"].str.split('process').str[1].str.split('h').str[0]
df_gplmdca["m"] = df_gplmdca["Execution_time"].str.split('process').str[1].str.split('h').str[1].str.split('min').str[0]
df_gplmdca["s"] = df_gplmdca["Execution_time"].str.split('process').str[1].str.split('h').str[1].str.split('min').str[1].str.split('s').str[0]
df_gplmdca

C:\Users\Yumika\AppData\Local\Temp\ipykernel_1916\368034067.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_gplmdca["h"] = df_gplmdca["Execution_time"].str.split('process').str[1].str.split('h').str[0]
C:\Users\Yumika\AppData\Local\Temp\ipykernel_1916\368034067.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_gplmdca["m"] = df_gplmdca["Execution_time"].str.split('process').str[1].str.split('h').str[1].str.split('min').str[0]
C:\Users\Yumika\AppData\Local\Temp\ipykernel_1916\368034067.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_gplmdca["s"] = df_gplmdca["Execution_time"].str.split('process').str[1].str.split('h').str[1].str.split('min').str[1].str.split('s').str[0]

,Filename,Execution_time,Bin,h,m,s
1,ENSP00000255194,58 min 52 s elapsed for process 10 h 58 min 52...,1090_1099,10,58,52
2,ENSP00000261778,1 min 18 s elapsed for process 17 h 1 min 18 s...,1090_1099,17,1,18
3,ENSP00000263409,29 min 49 s elapsed for process 14 h 29 min 49...,1090_1099,14,29,49
4,ENSP00000264160,18 min 10 s elapsed for process 9 h 18 min 10 ...,1090_1099,9,18,10
5,ENSP00000264868,11 min 5 s elapsed for process 5 h 11 min 5 s ...,1090_1099,5,11,5
...,...,...,...,...,...,...
616,ENSP00000504562,3 min 31 s elapsed for process 0 h 3 min 31 s ...,90_99,0,3,31
617,ENSP00000505395,2 min 5 s elapsed for process 0 h 2 min 5 s el...,90_99,0,2,5
618,ENSP00000512455,1 min 19 s elapsed for process 0 h 1 min 19 s ...,90_99,0,1,19
619,ENSP00000512643,Minimizing g_r for node r=92 Minimizing g_r fo...,90_99,NaN,NaN,NaN
620,ENSP00000512834,1 min 53 s elapsed for process 0 h 1 min 53 s ...,90_99,0,1,53

In [18]:
df_gplmdca.dtypes

Filename          object
Execution_time    object
Bin               object
h                 object
m                 object
s                 object
dtype: object

In [19]:
df_gplmdca = df_gplmdca.dropna()

In [20]:
df_gplmdca["h"] = df_gplmdca["h"].astype(int)
df_gplmdca["m"] = df_gplmdca["m"].astype(int)
df_gplmdca["s"] = df_gplmdca["s"].astype(int)
print(df_gplmdca.dtypes)
print(df_gplmdca)

Filename          object
Execution_time    object
Bin               object
h                  int32
m                  int32
s                  int32
dtype: object
            Filename                                     Execution_time  \
1    ENSP00000255194  58 min 52 s elapsed for process 10 h 58 min 52...
2    ENSP00000261778  1 min 18 s elapsed for process 17 h 1 min 18 s...
3    ENSP00000263409  29 min 49 s elapsed for process 14 h 29 min 49...
4    ENSP00000264160  18 min 10 s elapsed for process 9 h 18 min 10 ...
5    ENSP00000264868  11 min 5 s elapsed for process 5 h 11 min 5 s ...
..               ...                                                ...
615  ENSP00000502347  2 min 43 s elapsed for process 0 h 2 min 43 s ...
616  ENSP00000504562  3 min 31 s elapsed for process 0 h 3 min 31 s ...
617  ENSP00000505395  2 min 5 s elapsed for process 0 h 2 min 5 s el...
618  ENSP00000512455  1 min 19 s elapsed for process 0 h 1 min 19 s ...
620  ENSP00000512834  1 min 53 s elapsed for process 0 h 1 min 53 s ...

           Bin   h   m   s
1    1090_1099  10  58  52
2    1090_1099  17   1  18
3    1090_1099  14  29  49
4    1090_1099   9  18  10
5    1090_1099   5  11   5
..         ...  ..  ..  ..
615      90_99   0   2  43
616      90_99   0   3  31
617      90_99   0   2   5
618      90_99   0   1  19
620      90_99   0   1  53

[565 rows x 6 columns]

C:\Users\Yumika\AppData\Local\Temp\ipykernel_1916\1092703442.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_gplmdca["h"] = df_gplmdca["h"].astype(int)
C:\Users\Yumika\AppData\Local\Temp\ipykernel_1916\1092703442.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_gplmdca["m"] = df_gplmdca["m"].astype(int)
C:\Users\Yumika\AppData\Local\Temp\ipykernel_1916\1092703442.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_gplmdca["s"] = df_gplmdca["s"].astype(int)

In [21]:
df_gplmdca["Total_s"] = df_gplmdca["h"] * 3600 + df_gplmdca["m"] * 60 + df_gplmdca["s"]
df_gplmdca

C:\Users\Yumika\AppData\Local\Temp\ipykernel_1916\314820177.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_gplmdca["Total_s"] = df_gplmdca["h"] * 3600 + df_gplmdca["m"] * 60 + df_gplmdca["s"]

,Filename,Execution_time,Bin,h,m,s,Total_s
1,ENSP00000255194,58 min 52 s elapsed for process 10 h 58 min 52...,1090_1099,10,58,52,39532
2,ENSP00000261778,1 min 18 s elapsed for process 17 h 1 min 18 s...,1090_1099,17,1,18,61278
3,ENSP00000263409,29 min 49 s elapsed for process 14 h 29 min 49...,1090_1099,14,29,49,52189
4,ENSP00000264160,18 min 10 s elapsed for process 9 h 18 min 10 ...,1090_1099,9,18,10,33490
5,ENSP00000264868,11 min 5 s elapsed for process 5 h 11 min 5 s ...,1090_1099,5,11,5,18665
...,...,...,...,...,...,...,...
615,ENSP00000502347,2 min 43 s elapsed for process 0 h 2 min 43 s ...,90_99,0,2,43,163
616,ENSP00000504562,3 min 31 s elapsed for process 0 h 3 min 31 s ...,90_99,0,3,31,211
617,ENSP00000505395,2 min 5 s elapsed for process 0 h 2 min 5 s el...,90_99,0,2,5,125
618,ENSP00000512455,1 min 19 s elapsed for process 0 h 1 min 19 s ...,90_99,0,1,19,79
620,ENSP00000512834,1 min 53 s elapsed for process 0 h 1 min 53 s ...,90_99,0,1,53,113

## Merging each of the 2 dfs

## pydca

In [ ]:
# Merge pydca dfs
df_master_pydca = df_pydca.merge(df_base_pydca, how='inner', on='Filename')
df_master_pydca

In [ ]:
df_master_pydca = df_master_pydca[df_master_pydca["Sequence_length"] != 0]

### Re-binning based on seuqnece length

In [ ]:
# Re-grouping based on sequence length
df_master_pydca.loc[df_master_pydca['Sequence_length'] <= 99, 'seqlen_bin'] = '_99'
df_master_pydca.loc[df_master_pydca['Sequence_length'].between(100,199), 'seqlen_bin'] = '100_199'
df_master_pydca.loc[df_master_pydca['Sequence_length'].between(200,299), 'seqlen_bin'] = '200_299'
df_master_pydca.loc[df_master_pydca['Sequence_length'].between(300,499), 'seqlen_bin'] = '300_499'
df_master_pydca.loc[df_master_pydca['Sequence_length'].between(500,699), 'seqlen_bin'] = '500_699'
df_master_pydca.loc[df_master_pydca['Sequence_length'].between(700,899), 'seqlen_bin'] = '700_899'
df_master_pydca.loc[df_master_pydca['Sequence_length'].between(900,1099), 'seqlen_bin'] = '900_1099'
df_master_pydca.loc[df_master_pydca['Sequence_length'].between(1100,1299), 'seqlen_bin'] = '1100_1299'
df_master_pydca.loc[df_master_pydca['Sequence_length'].between(1300,1399), 'seqlen_bin'] = '1300_1399'

In [ ]:
df_master_pydca

In [ ]:
df_master_pydca.describe()

In [ ]:
binsize = 100
list_bins = [i for i in range (0, 1200, binsize)]
plt.hist(df_master_pydca["Sequence_length"], bins=list_bins)
plt.suptitle("Sequence length Distribution: n = " + str(df_master_pydca["Sequence_length"].shape[0]))
plt.title("bin size: " + str(binsize))
plt.xlabel("Sequence length")
plt.ylabel("Frequency")

## Obtaining the results

In [ ]:
## Obtaining the results
df_abin = df_master_pydca[df_master_pydca["seqlen_bin"] == "1100_1299"]
df_abin
bins = [-1, 250, 500, 750, 1000, 1250, np.inf]
labels=["-250", "250-500", "500-750", "750-1000", "1000-1250", "1250-"]
df_abin_grouped = df_abin.groupby(pd.cut(df_abin["MSA_size"], bins=bins, labels=labels)).mean()
#df_abin_grouped = df_abin.groupby(pd.cut(df_abin["MSA_size"], bins=bins, labels=labels)).size().reset_index(name='count')
df_abin_grouped

## gplmdca

In [22]:
# Merge gplmdca dfs
df_master_gplmdca = df_gplmdca.merge(df_base_gplmdca, how='inner', on='Filename')
df_master_gplmdca

,Filename,Execution_time,Bin_x,h,m,s,Total_s,MSA_size,Sequence_length,Bin_y
0,ENSP00000255194,58 min 52 s elapsed for process 10 h 58 min 52...,1090_1099,10,58,52,39532,334,1094,1090_1099
1,ENSP00000261778,1 min 18 s elapsed for process 17 h 1 min 18 s...,1090_1099,17,1,18,61278,766,1094,1090_1099
2,ENSP00000263409,29 min 49 s elapsed for process 14 h 29 min 49...,1090_1099,14,29,49,52189,311,1097,1090_1099
3,ENSP00000264160,18 min 10 s elapsed for process 9 h 18 min 10 ...,1090_1099,9,18,10,33490,137,1099,1090_1099
4,ENSP00000264868,11 min 5 s elapsed for process 5 h 11 min 5 s ...,1090_1099,5,11,5,18665,195,1097,1090_1099
...,...,...,...,...,...,...,...,...,...,...
560,ENSP00000502347,2 min 43 s elapsed for process 0 h 2 min 43 s ...,90_99,0,2,43,163,1082,95,90_99
561,ENSP00000504562,3 min 31 s elapsed for process 0 h 3 min 31 s ...,90_99,0,3,31,211,989,90,90_99
562,ENSP00000505395,2 min 5 s elapsed for process 0 h 2 min 5 s el...,90_99,0,2,5,125,320,99,90_99
563,ENSP00000512455,1 min 19 s elapsed for process 0 h 1 min 19 s ...,90_99,0,1,19,79,139,95,90_99
564,ENSP00000512834,1 min 53 s elapsed for process 0 h 1 min 53 s ...,90_99,0,1,53,113,818,96,90_99

In [23]:
# Keep only rows where Sequence_length is not 0
df_master_gplmdca = df_master_gplmdca[df_master_gplmdca["Sequence_length"] != 0]
df_master_gplmdca

,Filename,Execution_time,Bin_x,h,m,s,Total_s,MSA_size,Sequence_length,Bin_y
0,ENSP00000255194,58 min 52 s elapsed for process 10 h 58 min 52...,1090_1099,10,58,52,39532,334,1094,1090_1099
1,ENSP00000261778,1 min 18 s elapsed for process 17 h 1 min 18 s...,1090_1099,17,1,18,61278,766,1094,1090_1099
2,ENSP00000263409,29 min 49 s elapsed for process 14 h 29 min 49...,1090_1099,14,29,49,52189,311,1097,1090_1099
3,ENSP00000264160,18 min 10 s elapsed for process 9 h 18 min 10 ...,1090_1099,9,18,10,33490,137,1099,1090_1099
4,ENSP00000264868,11 min 5 s elapsed for process 5 h 11 min 5 s ...,1090_1099,5,11,5,18665,195,1097,1090_1099
...,...,...,...,...,...,...,...,...,...,...
560,ENSP00000502347,2 min 43 s elapsed for process 0 h 2 min 43 s ...,90_99,0,2,43,163,1082,95,90_99
561,ENSP00000504562,3 min 31 s elapsed for process 0 h 3 min 31 s ...,90_99,0,3,31,211,989,90,90_99
562,ENSP00000505395,2 min 5 s elapsed for process 0 h 2 min 5 s el...,90_99,0,2,5,125,320,99,90_99
563,ENSP00000512455,1 min 19 s elapsed for process 0 h 1 min 19 s ...,90_99,0,1,19,79,139,95,90_99
564,ENSP00000512834,1 min 53 s elapsed for process 0 h 1 min 53 s ...,90_99,0,1,53,113,818,96,90_99

In [35]:
df_abin = df_master_gplmdca[df_master_gplmdca["Bin_x"] == "1290_1399"]
bins = [-1, 250, 500, 750, 1000, 1250, np.inf]
labels=["-250", "250-500", "500-750", "750-1000", "1000-1250", "1250-"]
df_abin_grouped = df_abin.groupby(pd.cut(df_abin["MSA_size"], bins=bins, labels=labels)).size().reset_index(name='count')
df_abin_grouped

    MSA_size  count
0       -250     30
1    250-500      7
2    500-750      0
3   750-1000      0
4  1000-1250      0
5      1250-      0

In [ ]:
df_master_gplmdca.describe()

In [ ]:
binsize = 100
list_bins = [i for i in range (0, 1400, binsize)]
plt.hist(df_master_gplmdca["Sequence_length"], bins=list_bins)
plt.suptitle("Sequence length Distribution: n = " + str(df_master_gplmdca["Sequence_length"].shape[0]))
plt.title("bin size: " + str(binsize))
plt.xlabel("Sequence length")
plt.ylabel("Frequency")

## Obtaining the results

In [ ]:
df_abin = df_master_gplmdca[df_master_gplmdca["Bin_x"] == "1290_1399"]
bins = [-1, 250, 500, 750, 1000, 1250, np.inf]
labels=["-250", "250-500", "500-750", "750-1000", "1000-1250", "1250-"]
df_abin_grouped = df_abin.groupby(pd.cut(df_abin["MSA_size"], bins=bins, labels=labels)).mean()
df_abin_grouped

## Graphing MSA size distribution

In [ ]:
binsize = 250
list_bins = [i for i in range (0, 2000, binsize)]
plt.hist(df_master_gplmdca["MSA_size"], bins=list_bins)
plt.suptitle("MSA size Distribution: n = " + str(df_master_gplmdca["MSA_size"].shape[0]))
plt.title("bin size: " + str(binsize))
plt.xlabel("MSA Size")
plt.ylabel("Frequency")

## Merge the two merged dataframes

In [ ]:
df_master = df_master_gplmdca.merge(df_master_pydca, how="inner", on="Filename", suffixes=('_gplmdca', '_pydca'))
df_master

In [ ]:
df_master["Sequence_length"].value_counts()

In [ ]:
df_master[df_master["Sequence_length"] == 0].value_counts("Total_s_y")

In [ ]:
df_master['Bin_match'] = np.where(df_master['Bin_x'] == df_master['Bin_y'], 
                                           'yes', 'no')
df_master["Bin_match"].value_counts()

In [ ]:
df_succ = df_master[["Filename", "Total_s_gplmdca", "MSA_size_gplmdca", "Sequence_length_gplmdca", "Total_s_pydca", "MSA_size_pydca", "Sequence_length_pydca", "Bin_x_gplmdca", "h_gplmdca", "m_gplmdca", "s_gplmdca","Bin_x_pydca", "h_pydca", "m_pydca", "s_pydca"]]
df_succ

In [ ]:
df_abin = df_succ[df_succ["Bin_x_pydca"] == "90_99"]
df_abin

In [ ]:
df_abin.describe()

In [ ]:
binsize = 250
list_bins = [i for i in range (0, 10000, binsize)]
plt.hist(df_abin["MSA_size"], bins=list_bins)
plt.suptitle("MSA size Distribution: n = " + str(df_abin["MSA_size"].shape[0]))
plt.title("bin size: " + str(binsize))
plt.xlabel("MSA Size")
plt.ylabel("Frequency")